# Generated by Django 4.0.6 on 2022-07-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Client_name')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='xlsx/%y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=20, unique=True, verbose_name='Client_organization')),
                ('address', models.CharField(max_length=20, unique=True, verbose_name='Client_address')),
                ('fraud_weight', models.IntegerField(default=0)),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberorg', models.IntegerField()),
                ('sumcl', models.IntegerField()),
                ('date', models.DateField()),
                ('service', models.CharField(max_length=20)),
                ('fraud_score', models.FloatField()),
                ('service_class', models.IntegerField()),
                ('service_name', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientorg')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientorg',
            constraint=models.UniqueConstraint(fields=('address', 'org'), name='unique_address'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('numberorg', 'org'), name='unique_number'),
        ),
    ]
