# Generated by Django 4.0.6 on 2022-07-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorg',
            name='fraud_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
