# Generated by Django 4.0.6 on 2022-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('numberorg', 'org'), name='unique_number'),
        ),
    ]
