# Generated by Django 4.0.6 on 2022-07-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bill_fraud_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='number',
            new_name='numberorg',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='sum',
            new_name='sumcl',
        ),
    ]
