# Generated by Django 4.0.6 on 2022-07-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bill_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='numberorg',
            field=models.IntegerField(),
        ),
    ]
